app:
  flow:
    - id: 1024
#      routeExpr: ${in.storeId} == [xx]
      name: 默认审方流程
      basePackage: org.rx.demo.gjprescription.service.biz.action.impl
      stages:
        - id: 1
          name: 问诊阶段
          scopes:
            - ${doctorId} + ${patientId}
            - ${inquiryId}
          rules:
            - ordinal: 1
              method: HyDoctorAction.startInquiry
            - ordinal: 2
              method: HyDoctorAction.makePrescription
              events:
                - ordinal: 1
                  eventType: Pre/Post
                  async: true/false
                  beanType: org.rx.xxx.PostMakePrescriptionEventDto
                  beanBuilder:
                    doctorId: ${prev.in.doctorId}
                    inquiryId: ${in.inquiryId}
                    prescriptionNo: ${out.prescriptions[0].prescriptionNo}
                    patientAge: 10
                    time: ${now}
                - ordinal: 2
                  beanType: org.rx.xxx.SendMsgEventDto
                  beanBuilder:
                    doctorId: ${prev.in.doctorId}
                    inquiryId: ${in.inquiryId}
                    prescriptionNo: ${out.prescriptions[0].prescriptionNo}
            - ordinal: 3
              method: HyDoctorAction.endInquiry
        - id: 2
          name: 发药阶段
          rules:
            - ordinal: 1
              method: HyPharmacistAction.auditPrescription
            - ordinal: 1
              method: FyPharmacistAction.auditPrescription


  nameserver:
    - ns.f-li.cn:853
  processor:
    - queue:
        - name: 华山医院皮肤科
        - capacity: 1000000
        - kind: LOCAL_H2
      dispatcher:
        store: LOCAL_H2
        selector: DEFAULT
#    - queue:
#        - name: 华山医院（总院+分院）皮肤科
#        - capacity: 1000000
#        - kind: SHARDING_H2
#      dispatcher:
#        store: SHARDING_H2
#        selector: DEFAULT
