app:
  flow:
    - id: 1024
#      ruleExpr: ${in.storeid=[xx]}
      name: 默认审方流程
      basePackage: org.rx.demo.gjprescription.service.biz.action.impl
      rules:
        - id: 1
          actions:
            - ordinal: 1
              method: HyDoctorAction.startInquiry
            - ordinal: 2
              method: HyDoctorAction.makePrescription
            - ordinal: 3
              method: HyDoctorAction.endInquiry
        - id: 2
          actions:
            - ordinal: 1
              method: HyPharmacistAction.auditPrescription
            - ordinal: 1
              method: FyPharmacistAction.auditPrescription


  nameserver:
    - ns.f-li.cn:853
  processor:
    - queue:
        - name: 华山医院皮肤科
        - capacity: 1000000
        - kind: LOCAL_H2
      dispatcher:
        store: LOCAL_H2
        selector: DEFAULT
#    - queue:
#        - name: 华山医院（总院+分院）皮肤科
#        - capacity: 1000000
#        - kind: SHARDING_H2
#      dispatcher:
#        store: SHARDING_H2
#        selector: DEFAULT
